site_name: JHutch Docs

site_url: https://mydomain.org/mysite
theme:
  name: material
  
  theme:
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto 
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: amber 

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: teal 
      accent: amber
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path 
    - navigation.indexes 
    - navigation.sections
    

nav: 
  - Home: index.md
  - About: about.md 
  - Portfolio: 
    - Portfolio/index.md 
    - College Surplus Sale: Portfolio/college surplus sale.md 
  - Resume: Resume.md 
  - Personal: Personal.md
  - Contact: Contact.md


    







